// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseURL: `${string}://${string}` | 'https://127.0.0.1:5000' | 'https://127.0.0.1:5000' | 'https://127.0.0.1:5000' | 'https://127.0.0.1:5000' | 'https://127.0.0.1:5000' | 'https://127.0.0.1:5000' | 'https://127.0.0.1:5000' | 'https://127.0.0.1:5000' | 'https://127.0.0.1:5008' | 'https://127.0.0.1:5008' | 'https://127.0.0.1:5008' | 'https://127.0.0.1:5008' | 'https://127.0.0.1:5008' | 'https://127.0.0.1:5008' | 'https://127.0.0.1:5008' | 'https://127.0.0.1:5008' | 'https://127.0.0.1:5008' | 'https://127.0.0.1:5008' | 'https://127.0.0.1:5008' | 'https://127.0.0.1:5008' | 'https://127.0.0.1:5003' | 'https://127.0.0.1:5003' | 'https://127.0.0.1:5003' | 'https://127.0.0.1:5003' | 'https://127.0.0.1:5003' | 'https://127.0.0.1:5003' | 'https://127.0.0.1:5003' | 'https://127.0.0.1:5003' | 'https://127.0.0.1:5006' | 'https://127.0.0.1:5006' | 'https://127.0.0.1:5006' | 'https://127.0.0.1:5006' | (string & {});
};

export type SignInWithEmailAndPasswordData = {
    body: {
        email: string;
        password: string;
    };
    path?: never;
    query?: {
        login_challenge?: string;
    };
    url: '/identity/signin';
};

export type SignInWithEmailAndPasswordResponses = {
    /**
     * Default Response
     */
    200: {
        data: {
            identity: {
                id: string;
                email: string;
                emailVerified?: boolean;
            };
            redirectTo?: string;
        };
    };
};

export type SignInWithEmailAndPasswordResponse = SignInWithEmailAndPasswordResponses[keyof SignInWithEmailAndPasswordResponses];

export type LogoutData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/identity/logout';
};

export type LogoutResponses = {
    /**
     * Default Response
     */
    200: {
        data: {
            message: string;
        };
    };
};

export type LogoutResponse = LogoutResponses[keyof LogoutResponses];

export type GetCurrentUserData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/identity/me';
};

export type GetCurrentUserResponses = {
    /**
     * Default Response
     */
    200: {
        data: {
            identity: {
                id: string;
                email: string;
                emailVerified?: boolean;
            };
            profile: {
                id: string;
                identityId: string;
                firstName: string;
                middleName?: string | null;
                lastName?: string | null;
                gender?: string | null;
                description?: string | null;
                photoUrl?: string | null;
                fullName: string;
            } | null;
        };
    };
};

export type GetCurrentUserResponse = GetCurrentUserResponses[keyof GetCurrentUserResponses];

export type GetIdentityFromSessionData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/identity/getIdentityFromSession';
};

export type GetIdentityFromSessionResponses = {
    /**
     * Default Response
     */
    200: {
        data: {
            identity: {
                id: string;
                email: string;
                emailVerified: boolean;
            };
        };
    };
};

export type GetIdentityFromSessionResponse = GetIdentityFromSessionResponses[keyof GetIdentityFromSessionResponses];

export type GetIdentityFromAccessTokenData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/identity/getIdentityFromAccessToken';
};

export type GetIdentityFromAccessTokenResponses = {
    /**
     * Default Response
     */
    200: {
        data: {
            identity: {
                id: string;
                email: string;
                emailVerified: boolean;
            };
        };
    };
};

export type GetIdentityFromAccessTokenResponse = GetIdentityFromAccessTokenResponses[keyof GetIdentityFromAccessTokenResponses];

export type RegisterData = {
    body: {
        email: string;
        username: string;
        password: string;
    };
    path?: never;
    query?: never;
    url: '/identity/register';
};

export type RegisterResponses = {
    /**
     * Default Response
     */
    200: {
        data: {
            message: string;
        };
    };
};

export type RegisterResponse = RegisterResponses[keyof RegisterResponses];

export type VerifyEmailData = {
    body?: never;
    path?: never;
    query: {
        flow: string;
        code: string;
    };
    url: '/identity/verifyEmail';
};

export type VerifyEmailResponses = {
    /**
     * Default Response
     */
    200: {
        data: {
            message: string;
        };
    };
};

export type VerifyEmailResponse = VerifyEmailResponses[keyof VerifyEmailResponses];

export type ResendVerificationEmailData = {
    body: {
        email: string;
    };
    path?: never;
    query?: never;
    url: '/identity/resendVerificationEmail';
};

export type ResendVerificationEmailResponses = {
    /**
     * Default Response
     */
    200: {
        data: {
            message: string;
        };
    };
};

export type ResendVerificationEmailResponse = ResendVerificationEmailResponses[keyof ResendVerificationEmailResponses];

export type AuthorizeData = {
    body?: never;
    path?: never;
    query?: {
        response_type?: 'code';
        client_id?: string;
        redirect_uri?: string;
        scope?: string;
        state?: string;
        code_challenge?: string;
        code_challenge_method?: 'S256' | 'plain';
        nonce?: string;
        login_verifier?: string;
        consent_verifier?: string;
    };
    url: '/oauth/authorize';
};

export type AcceptLoginChallengeData = {
    body: {
        challenge: string;
        subject: string;
        remember?: boolean;
        rememberFor?: number;
        identityProviderSessionId?: string;
    };
    path?: never;
    query?: never;
    url: '/internal/oauth/login/accept';
};

export type AcceptLoginChallengeResponses = {
    /**
     * Default Response
     */
    200: {
        data: {
            redirectTo: string;
        };
    };
};

export type AcceptLoginChallengeResponse = AcceptLoginChallengeResponses[keyof AcceptLoginChallengeResponses];

export type GetConsentChallengeData = {
    body?: never;
    path?: never;
    query: {
        consent_challenge: string;
    };
    url: '/oauth/consent';
};

export type GetConsentChallengeResponses = {
    /**
     * Default Response
     */
    200: {
        data: {
            challenge: string;
            skip: boolean;
            subject?: string;
            client: {
                id: string;
                name?: string;
                redirectUris?: Array<string>;
            };
            requestedScope: Array<string>;
            scopes: Array<{
                scope: string;
                title: string;
                description: string;
            }>;
            loginChallenge?: string;
            loginSessionId?: string;
        };
    };
};

export type GetConsentChallengeResponse = GetConsentChallengeResponses[keyof GetConsentChallengeResponses];

export type AcceptConsentChallengeData = {
    body: {
        grantScope: Array<string>;
        remember?: boolean;
        rememberFor?: number;
    };
    path?: never;
    query: {
        consent_challenge: string;
    };
    url: '/oauth/consent/accept';
};

export type AcceptConsentChallengeResponses = {
    /**
     * Default Response
     */
    200: {
        data: {
            redirectTo: string;
        };
    };
};

export type AcceptConsentChallengeResponse = AcceptConsentChallengeResponses[keyof AcceptConsentChallengeResponses];

export type RejectConsentChallengeData = {
    body: {
        error?: string;
        errorDescription?: string;
    };
    path?: never;
    query: {
        consent_challenge: string;
    };
    url: '/oauth/consent/reject';
};

export type RejectConsentChallengeResponses = {
    /**
     * Default Response
     */
    200: {
        data: {
            redirectTo: string;
        };
    };
};

export type RejectConsentChallengeResponse = RejectConsentChallengeResponses[keyof RejectConsentChallengeResponses];

export type ExchangeTokenData = {
    body: {
        grant_type: 'authorization_code';
        code: string;
        client_id: string;
        redirect_uri: string;
        code_verifier: string;
    };
    path?: never;
    query?: never;
    url: '/oauth/token';
};

export type ExchangeTokenResponses = {
    /**
     * Default Response
     */
    200: {
        data: {
            message: string;
        };
    };
};

export type ExchangeTokenResponse = ExchangeTokenResponses[keyof ExchangeTokenResponses];

export type IntrospectTokenData = {
    body: {
        token: string;
        scope?: string;
    };
    path?: never;
    query?: never;
    url: '/oauth/introspect';
};

export type IntrospectTokenResponses = {
    /**
     * Default Response
     */
    200: {
        data: {
            active: boolean;
            subject?: string;
            clientId?: string;
            scope?: string;
            expiresAt?: string;
            issuedAt?: string;
            audience?: Array<string>;
            extra?: {
                [key: string]: unknown;
            };
        };
    };
};

export type IntrospectTokenResponse = IntrospectTokenResponses[keyof IntrospectTokenResponses];

export type CreateOAuthClientData = {
    body: {
        name: string;
        redirectUris?: Array<string>;
        scopes?: Array<string>;
        grantTypes: Array<string>;
    };
    path?: never;
    query?: never;
    url: '/oauth/clients';
};

export type CreateOAuthClientResponses = {
    /**
     * Default Response
     */
    200: {
        data: {
            id: string;
            name: string;
            redirectUris: Array<string>;
            scopes: Array<string>;
            grantTypes: Array<string>;
        };
    };
};

export type CreateOAuthClientResponse = CreateOAuthClientResponses[keyof CreateOAuthClientResponses];

export type DeleteOAuthClientData = {
    body?: never;
    path: {
        clientId: string;
    };
    query?: never;
    url: '/oauth/clients/{clientId}';
};

export type DeleteOAuthClientResponses = {
    /**
     * Default Response
     */
    200: {
        data: {
            deleted: boolean;
        };
    };
};

export type DeleteOAuthClientResponse = DeleteOAuthClientResponses[keyof DeleteOAuthClientResponses];

export type GetOAuthClientData = {
    body?: never;
    path: {
        clientId: string;
    };
    query?: never;
    url: '/oauth/clients/{clientId}';
};

export type GetOAuthClientResponses = {
    /**
     * Default Response
     */
    200: {
        data: {
            id: string;
            name: string;
            redirectUris: Array<string>;
            scopes: Array<string>;
            grantTypes: Array<string>;
        };
    };
};

export type GetOAuthClientResponse = GetOAuthClientResponses[keyof GetOAuthClientResponses];

export type GetOpenIdConfigurationData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/oauth/.well-known/openid-configuration';
};

export type GetOpenIdConfigurationResponses = {
    /**
     * Default Response
     */
    200: {
        issuer: string;
        authorization_endpoint: string;
        token_endpoint: string;
        jwks_uri: string;
        introspection_endpoint: string;
        [key: string]: unknown;
    };
};

export type GetOpenIdConfigurationResponse = GetOpenIdConfigurationResponses[keyof GetOpenIdConfigurationResponses];

export type GetJwksData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/oauth/.well-known/jwks.json';
};

export type GetJwksResponses = {
    /**
     * Default Response
     */
    200: {
        keys: Array<{
            [key: string]: unknown;
        }>;
    };
};

export type GetJwksResponse = GetJwksResponses[keyof GetJwksResponses];

export type GetAttachmentDerivativeData = {
    body?: never;
    path: {
        attachmentId: string;
        derivativeType: 'thumbnail' | 'preview';
    };
    query?: never;
    url: '/attachments/{attachmentId}/derivatives/{derivativeType}';
};

export type GetAttachmentDerivativeResponses = {
    /**
     * Default Response
     */
    200: unknown;
};

export type StoreAttachmentDerivativeData = {
    body?: never;
    path: {
        attachmentId: string;
        versionId: string;
        derivativeType: 'thumbnail' | 'preview';
    };
    query?: never;
    url: '/internal/attachments/{attachmentId}/versions/{versionId}/derivatives/{derivativeType}';
};

export type StoreAttachmentDerivativeResponses = {
    /**
     * Default Response
     */
    200: {
        data: {
            derivativeId: string;
            attachmentId: string;
            versionId: string;
            derivativeType: string;
            mimeType: string;
            fileSize: number;
            width: number;
            height: number;
        };
    };
};

export type StoreAttachmentDerivativeResponse = StoreAttachmentDerivativeResponses[keyof StoreAttachmentDerivativeResponses];

export type StoreAttachmentMetadataData = {
    body: {
        width?: number;
        height?: number;
        format?: string;
        space?: string;
        channels?: number;
        density?: number;
        hasAlpha?: boolean;
        orientation?: number;
        extractedAt: string;
    };
    path: {
        attachmentId: string;
        versionId: string;
    };
    query?: never;
    url: '/internal/attachments/{attachmentId}/versions/{versionId}/metadata';
};

export type StoreAttachmentMetadataResponses = {
    /**
     * Default Response
     */
    200: {
        data: {
            metadataId: string;
            attachmentId: string;
            versionId: string;
            width?: number;
            height?: number;
            format?: string;
            space?: string;
            channels?: number;
            density?: number;
            hasAlpha?: boolean;
            orientation?: number;
            extractedAt: string;
        };
    };
};

export type StoreAttachmentMetadataResponse = StoreAttachmentMetadataResponses[keyof StoreAttachmentMetadataResponses];

export type GetAttachmentContentData = {
    body?: never;
    path: {
        attachmentId: string;
    };
    query?: never;
    url: '/attachments/{attachmentId}';
};

export type GetAttachmentContentResponses = {
    /**
     * Default Response
     */
    200: unknown;
};

export type GetAttachmentVersionContentData = {
    body?: never;
    path: {
        attachmentId: string;
        versionId: string;
    };
    query?: never;
    url: '/internal/attachments/{attachmentId}/versions/{versionId}/content';
};

export type GetAttachmentVersionContentResponses = {
    /**
     * Default Response
     */
    200: unknown;
};

export type UpdateSecurityStatusData = {
    body: {
        status: 'CLEAN' | 'INFECTED' | 'FAILED';
    };
    path: {
        attachmentId: string;
    };
    query?: never;
    url: '/internal/attachments/{attachmentId}/security-status';
};

export type UpdateSecurityStatusResponses = {
    /**
     * Default Response
     */
    200: {
        data: {
            attachmentId: string;
            status: string;
            securityStatus: string;
        };
    };
};

export type UpdateSecurityStatusResponse = UpdateSecurityStatusResponses[keyof UpdateSecurityStatusResponses];

export type CreateUploadTargetData = {
    body: {
        scopeType: 'IDENTITY' | 'ORGANIZATION';
        scopeId: string;
        tenantId?: string;
        filename: string;
        contentType: string;
        size: number;
        operationId?: string;
        metadata?: {
            [key: string]: unknown;
        };
    };
    path?: never;
    query?: never;
    url: '/internal/attachments/createUploadTarget';
};

export type CreateUploadTargetResponses = {
    /**
     * Default Response
     */
    200: {
        data: {
            objectId: string;
            url: string;
            headers: {
                [key: string]: string;
            };
            expiresAt: string;
        };
    };
};

export type CreateUploadTargetResponse = CreateUploadTargetResponses[keyof CreateUploadTargetResponses];

export type UploadToTargetData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/attachments/upload/{id}';
};

export type UploadToTargetResponses = {
    /**
     * Default Response
     */
    200: {
        data: {
            status: string;
        };
    };
};

export type UploadToTargetResponse = UploadToTargetResponses[keyof UploadToTargetResponses];

export type CheckRelationshipData = {
    body: {
        namespace: 'Identity' | 'Profile' | 'Platform' | 'Tenant' | 'Organization' | 'Space' | 'List' | 'Item' | 'Role' | 'Permission';
        object: string;
        relation: string;
        subject: string;
    };
    path?: never;
    query?: never;
    url: '/authorization/checkRelationship';
};

export type CheckRelationshipResponses = {
    /**
     * Default Response
     */
    200: {
        data: {
            allowed: boolean;
        };
    };
};

export type CheckRelationshipResponse = CheckRelationshipResponses[keyof CheckRelationshipResponses];

export type EnsureRelationshipData = {
    body: {
        object: {
            namespace: 'Identity' | 'Profile' | 'Platform' | 'Tenant' | 'Organization' | 'Space' | 'List' | 'Item' | 'Role' | 'Permission';
            id: string;
        };
        relation: string;
        subject?: {
            namespace: 'Identity' | 'Profile' | 'Platform' | 'Tenant' | 'Organization' | 'Space' | 'List' | 'Item' | 'Role' | 'Permission';
            id: string;
        };
        subjectSet?: {
            namespace: 'Identity' | 'Profile' | 'Platform' | 'Tenant' | 'Organization' | 'Space' | 'List' | 'Item' | 'Role' | 'Permission';
            id: string;
            relation: string;
        };
    };
    path?: never;
    query?: never;
    url: '/authorization/ensureRelationship';
};

export type EnsureRelationshipResponses = {
    /**
     * Default Response
     */
    200: {
        data: {
            created: boolean;
        };
    };
};

export type EnsureRelationshipResponse = EnsureRelationshipResponses[keyof EnsureRelationshipResponses];

export type DeleteRelationshipData = {
    body: {
        object: {
            namespace: 'Identity' | 'Profile' | 'Platform' | 'Tenant' | 'Organization' | 'Space' | 'List' | 'Item' | 'Role' | 'Permission';
            id: string;
        };
        relation: string;
        subject?: {
            namespace: 'Identity' | 'Profile' | 'Platform' | 'Tenant' | 'Organization' | 'Space' | 'List' | 'Item' | 'Role' | 'Permission';
            id: string;
        };
        subjectSet?: {
            namespace: 'Identity' | 'Profile' | 'Platform' | 'Tenant' | 'Organization' | 'Space' | 'List' | 'Item' | 'Role' | 'Permission';
            id: string;
            relation: string;
        };
    };
    path?: never;
    query?: never;
    url: '/authorization/deleteRelationship';
};

export type DeleteRelationshipResponses = {
    /**
     * Default Response
     */
    200: {
        data: {
            deleted: boolean;
        };
    };
};

export type DeleteRelationshipResponse = DeleteRelationshipResponses[keyof DeleteRelationshipResponses];

export type ListRelationshipsData = {
    body: {
        namespace: 'Identity' | 'Profile' | 'Platform' | 'Tenant' | 'Organization' | 'Space' | 'List' | 'Item' | 'Role' | 'Permission';
        object?: string;
        relation?: string;
        subject?: {
            namespace: 'Identity' | 'Profile' | 'Platform' | 'Tenant' | 'Organization' | 'Space' | 'List' | 'Item' | 'Role' | 'Permission';
            id: string;
        };
    };
    path?: never;
    query?: never;
    url: '/authorization/listRelationships';
};

export type ListRelationshipsResponses = {
    /**
     * Default Response
     */
    200: {
        data: {
            relationships: Array<{
                object: {
                    namespace: 'Identity' | 'Profile' | 'Platform' | 'Tenant' | 'Organization' | 'Space' | 'List' | 'Item' | 'Role' | 'Permission';
                    id: string;
                };
                relation: string;
                subject?: {
                    namespace: 'Identity' | 'Profile' | 'Platform' | 'Tenant' | 'Organization' | 'Space' | 'List' | 'Item' | 'Role' | 'Permission';
                    id: string;
                };
                subjectSet?: {
                    namespace: 'Identity' | 'Profile' | 'Platform' | 'Tenant' | 'Organization' | 'Space' | 'List' | 'Item' | 'Role' | 'Permission';
                    id: string;
                    relation: string;
                };
            }>;
        };
    };
};

export type ListRelationshipsResponse = ListRelationshipsResponses[keyof ListRelationshipsResponses];
