// This file is auto-generated by @hey-api/openapi-ts

import type { Client, ClientMeta, Options as Options2, RequestResult, TDataShape } from './client';
import { client } from './client.gen';
import type { AcceptConsentChallengeData, AcceptConsentChallengeResponses, AcceptLoginChallengeData, AcceptLoginChallengeResponses, AuthorizeData, CheckRelationshipData, CheckRelationshipResponses, CreateOAuthClientData, CreateOAuthClientResponses, CreateUploadTargetData, CreateUploadTargetResponses, DeleteOAuthClientData, DeleteOAuthClientResponses, DeleteRelationshipData, DeleteRelationshipResponses, EnsureRelationshipData, EnsureRelationshipResponses, ExchangeTokenData, ExchangeTokenResponses, GetAttachmentContentData, GetAttachmentContentResponses, GetAttachmentDerivativeData, GetAttachmentDerivativeResponses, GetAttachmentVersionContentData, GetAttachmentVersionContentResponses, GetConsentChallengeData, GetConsentChallengeResponses, GetCurrentUserData, GetCurrentUserResponses, GetIdentityFromAccessTokenData, GetIdentityFromAccessTokenResponses, GetIdentityFromSessionData, GetIdentityFromSessionResponses, GetJwksData, GetJwksResponses, GetOAuthClientData, GetOAuthClientResponses, GetOpenIdConfigurationData, GetOpenIdConfigurationResponses, IntrospectTokenData, IntrospectTokenResponses, ListRelationshipsData, ListRelationshipsResponses, LogoutData, LogoutResponses, RegisterData, RegisterResponses, RejectConsentChallengeData, RejectConsentChallengeResponses, ResendVerificationEmailData, ResendVerificationEmailResponses, SignInWithEmailAndPasswordData, SignInWithEmailAndPasswordResponses, StoreAttachmentDerivativeData, StoreAttachmentDerivativeResponses, StoreAttachmentMetadataData, StoreAttachmentMetadataResponses, UpdateSecurityStatusData, UpdateSecurityStatusResponses, UploadToTargetData, UploadToTargetResponses, VerifyEmailData, VerifyEmailResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean, TResponse = unknown> = Options2<TData, ThrowOnError, TResponse> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: keyof ClientMeta extends never ? Record<string, unknown> : ClientMeta;
};

/**
 * Sign in with email and password
 *
 * Authenticate a user with email and password via the identity provider. Sets the session cookie. When a login_challenge is present, returns redirectTo for the OAuth provider.
 */
export const signInWithEmailAndPassword = <ThrowOnError extends boolean = false>(options: Options<SignInWithEmailAndPasswordData, ThrowOnError>): RequestResult<SignInWithEmailAndPasswordResponses, unknown, ThrowOnError> => (options.client ?? client).post<SignInWithEmailAndPasswordResponses, unknown, ThrowOnError>({
    responseType: 'json',
    url: '/identity/signin',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Logout
 *
 * Invalidate the current session and clear the session cookie
 */
export const logout = <ThrowOnError extends boolean = false>(options?: Options<LogoutData, ThrowOnError>): RequestResult<LogoutResponses, unknown, ThrowOnError> => (options?.client ?? client).post<LogoutResponses, unknown, ThrowOnError>({
    responseType: 'json',
    url: '/identity/logout',
    ...options
});

/**
 * Get current authenticated user
 *
 * Return basic information about the current user by verifying the session cookie
 */
export const getCurrentUser = <ThrowOnError extends boolean = false>(options?: Options<GetCurrentUserData, ThrowOnError>): RequestResult<GetCurrentUserResponses, unknown, ThrowOnError> => (options?.client ?? client).get<GetCurrentUserResponses, unknown, ThrowOnError>({
    responseType: 'json',
    url: '/identity/me',
    ...options
});

/**
 * Resolve session identity
 *
 * Verify the session cookie against Ory Kratos (SDK FrontendApi.toSession) and return the authenticated identity. Used by other services via @pine/identity.
 */
export const getIdentityFromSession = <ThrowOnError extends boolean = false>(options?: Options<GetIdentityFromSessionData, ThrowOnError>): RequestResult<GetIdentityFromSessionResponses, unknown, ThrowOnError> => (options?.client ?? client).get<GetIdentityFromSessionResponses, unknown, ThrowOnError>({
    responseType: 'json',
    url: '/identity/getIdentityFromSession',
    ...options
});

/**
 * Resolve identity from OAuth access token
 *
 * Introspect an OAuth provider access token (Authorization: Bearer) and return the authenticated identity. Used by other services via @pine/identity.
 */
export const getIdentityFromAccessToken = <ThrowOnError extends boolean = false>(options?: Options<GetIdentityFromAccessTokenData, ThrowOnError>): RequestResult<GetIdentityFromAccessTokenResponses, unknown, ThrowOnError> => (options?.client ?? client).get<GetIdentityFromAccessTokenResponses, unknown, ThrowOnError>({
    responseType: 'json',
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/identity/getIdentityFromAccessToken',
    ...options
});

/**
 * Register
 *
 * Register a new user with email and password via the identity provider
 */
export const register = <ThrowOnError extends boolean = false>(options: Options<RegisterData, ThrowOnError>): RequestResult<RegisterResponses, unknown, ThrowOnError> => (options.client ?? client).post<RegisterResponses, unknown, ThrowOnError>({
    responseType: 'json',
    url: '/identity/register',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Verify email with Kratos code
 *
 * Complete email verification using the one-time code from the Kratos verification email
 */
export const verifyEmail = <ThrowOnError extends boolean = false>(options: Options<VerifyEmailData, ThrowOnError>): RequestResult<VerifyEmailResponses, unknown, ThrowOnError> => (options.client ?? client).get<VerifyEmailResponses, unknown, ThrowOnError>({
    responseType: 'json',
    url: '/identity/verifyEmail',
    ...options
});

/**
 * Resend verification email
 *
 * Request a new email verification code. Always returns success to avoid revealing whether the email is registered.
 */
export const resendVerificationEmail = <ThrowOnError extends boolean = false>(options: Options<ResendVerificationEmailData, ThrowOnError>): RequestResult<ResendVerificationEmailResponses, unknown, ThrowOnError> => (options.client ?? client).post<ResendVerificationEmailResponses, unknown, ThrowOnError>({
    responseType: 'json',
    url: '/identity/resendVerificationEmail',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * OAuth authorize
 *
 * Start or continue the OAuth authorization code flow. Proxies the authorization server public authorize endpoint and returns its redirect.
 */
export const authorize = <ThrowOnError extends boolean = false>(options?: Options<AuthorizeData, ThrowOnError>): RequestResult<unknown, unknown, ThrowOnError> => (options?.client ?? client).get<unknown, unknown, ThrowOnError>({ url: '/oauth/authorize', ...options });

/**
 * Accept OAuth login challenge
 *
 * Accept an OAuth login challenge after the user authenticates
 */
export const acceptLoginChallenge = <ThrowOnError extends boolean = false>(options: Options<AcceptLoginChallengeData, ThrowOnError>): RequestResult<AcceptLoginChallengeResponses, unknown, ThrowOnError> => (options.client ?? client).post<AcceptLoginChallengeResponses, unknown, ThrowOnError>({
    responseType: 'json',
    url: '/internal/oauth/login/accept',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * OAuth consent challenge
 *
 * Load OAuth consent challenge details by consent_challenge
 */
export const getConsentChallenge = <ThrowOnError extends boolean = false>(options: Options<GetConsentChallengeData, ThrowOnError>): RequestResult<GetConsentChallengeResponses, unknown, ThrowOnError> => (options.client ?? client).get<GetConsentChallengeResponses, unknown, ThrowOnError>({
    responseType: 'json',
    url: '/oauth/consent',
    ...options
});

/**
 * Accept OAuth consent
 *
 * Accept an OAuth consent challenge with granted scopes
 */
export const acceptConsentChallenge = <ThrowOnError extends boolean = false>(options: Options<AcceptConsentChallengeData, ThrowOnError>): RequestResult<AcceptConsentChallengeResponses, unknown, ThrowOnError> => (options.client ?? client).post<AcceptConsentChallengeResponses, unknown, ThrowOnError>({
    responseType: 'json',
    url: '/oauth/consent/accept',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Reject OAuth consent
 *
 * Reject an OAuth consent challenge when the user denies access
 */
export const rejectConsentChallenge = <ThrowOnError extends boolean = false>(options: Options<RejectConsentChallengeData, ThrowOnError>): RequestResult<RejectConsentChallengeResponses, unknown, ThrowOnError> => (options.client ?? client).post<RejectConsentChallengeResponses, unknown, ThrowOnError>({
    responseType: 'json',
    url: '/oauth/consent/reject',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * OAuth token
 *
 * Exchange an authorization code for access (and optional refresh/id) tokens and set them as HTTP-only cookies
 */
export const exchangeToken = <ThrowOnError extends boolean = false>(options: Options<ExchangeTokenData, ThrowOnError>): RequestResult<ExchangeTokenResponses, unknown, ThrowOnError> => (options.client ?? client).post<ExchangeTokenResponses, unknown, ThrowOnError>({
    responseType: 'json',
    url: '/oauth/token',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Introspect OAuth token
 *
 * Introspect an access or refresh token via the OAuth provider
 */
export const introspectToken = <ThrowOnError extends boolean = false>(options: Options<IntrospectTokenData, ThrowOnError>): RequestResult<IntrospectTokenResponses, unknown, ThrowOnError> => (options.client ?? client).post<IntrospectTokenResponses, unknown, ThrowOnError>({
    responseType: 'json',
    url: '/oauth/introspect',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Create OAuth client
 *
 * Register a new OAuth 2.0 client with the authorization server
 */
export const createOAuthClient = <ThrowOnError extends boolean = false>(options: Options<CreateOAuthClientData, ThrowOnError>): RequestResult<CreateOAuthClientResponses, unknown, ThrowOnError> => (options.client ?? client).post<CreateOAuthClientResponses, unknown, ThrowOnError>({
    responseType: 'json',
    url: '/oauth/clients',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Delete OAuth client
 *
 * Delete an OAuth 2.0 client by client id
 */
export const deleteOAuthClient = <ThrowOnError extends boolean = false>(options: Options<DeleteOAuthClientData, ThrowOnError>): RequestResult<DeleteOAuthClientResponses, unknown, ThrowOnError> => (options.client ?? client).delete<DeleteOAuthClientResponses, unknown, ThrowOnError>({
    responseType: 'json',
    url: '/oauth/clients/{clientId}',
    ...options
});

/**
 * Get OAuth client
 *
 * Fetch an OAuth 2.0 client by client id
 */
export const getOAuthClient = <ThrowOnError extends boolean = false>(options: Options<GetOAuthClientData, ThrowOnError>): RequestResult<GetOAuthClientResponses, unknown, ThrowOnError> => (options.client ?? client).get<GetOAuthClientResponses, unknown, ThrowOnError>({
    responseType: 'json',
    url: '/oauth/clients/{clientId}',
    ...options
});

/**
 * OpenID Provider configuration
 *
 * OIDC discovery document for the public authorization server. Endpoint URLs use OAUTH_PUBLIC_URL.
 */
export const getOpenIdConfiguration = <ThrowOnError extends boolean = false>(options?: Options<GetOpenIdConfigurationData, ThrowOnError>): RequestResult<GetOpenIdConfigurationResponses, unknown, ThrowOnError> => (options?.client ?? client).get<GetOpenIdConfigurationResponses, unknown, ThrowOnError>({
    responseType: 'json',
    url: '/oauth/.well-known/openid-configuration',
    ...options
});

/**
 * JSON Web Key Set
 *
 * Public keys used to verify ID tokens issued by the authorization server.
 */
export const getJwks = <ThrowOnError extends boolean = false>(options?: Options<GetJwksData, ThrowOnError>): RequestResult<GetJwksResponses, unknown, ThrowOnError> => (options?.client ?? client).get<GetJwksResponses, unknown, ThrowOnError>({
    responseType: 'json',
    url: '/oauth/.well-known/jwks.json',
    ...options
});

/**
 * Get attachment derivative content stream
 *
 * Download thumbnail or preview derivative for an attachment current version
 */
export const getAttachmentDerivative = <ThrowOnError extends boolean = false>(options: Options<GetAttachmentDerivativeData, ThrowOnError>): RequestResult<GetAttachmentDerivativeResponses, unknown, ThrowOnError> => (options.client ?? client).get<GetAttachmentDerivativeResponses, unknown, ThrowOnError>({ url: '/attachments/{attachmentId}/derivatives/{derivativeType}', ...options });

/**
 * Store attachment derivative
 *
 * Store processed attachment derivative bytes (thumbnail or preview)
 */
export const storeAttachmentDerivative = <ThrowOnError extends boolean = false>(options: Options<StoreAttachmentDerivativeData, ThrowOnError>): RequestResult<StoreAttachmentDerivativeResponses, unknown, ThrowOnError> => (options.client ?? client).put<StoreAttachmentDerivativeResponses, unknown, ThrowOnError>({
    responseType: 'json',
    url: '/internal/attachments/{attachmentId}/versions/{versionId}/derivatives/{derivativeType}',
    ...options
});

/**
 * Store attachment metadata
 *
 * Store processed attachment image metadata and schedule event via outbox
 */
export const storeAttachmentMetadata = <ThrowOnError extends boolean = false>(options: Options<StoreAttachmentMetadataData, ThrowOnError>): RequestResult<StoreAttachmentMetadataResponses, unknown, ThrowOnError> => (options.client ?? client).post<StoreAttachmentMetadataResponses, unknown, ThrowOnError>({
    responseType: 'json',
    url: '/internal/attachments/{attachmentId}/versions/{versionId}/metadata',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Get attachment content stream
 *
 * Download raw current version content for an attachment
 */
export const getAttachmentContent = <ThrowOnError extends boolean = false>(options: Options<GetAttachmentContentData, ThrowOnError>): RequestResult<GetAttachmentContentResponses, unknown, ThrowOnError> => (options.client ?? client).get<GetAttachmentContentResponses, unknown, ThrowOnError>({ url: '/attachments/{attachmentId}', ...options });

/**
 * Get attachment version content stream
 *
 * Download raw attachment version content
 */
export const getAttachmentVersionContent = <ThrowOnError extends boolean = false>(options: Options<GetAttachmentVersionContentData, ThrowOnError>): RequestResult<GetAttachmentVersionContentResponses, unknown, ThrowOnError> => (options.client ?? client).get<GetAttachmentVersionContentResponses, unknown, ThrowOnError>({ url: '/internal/attachments/{attachmentId}/versions/{versionId}/content', ...options });

/**
 * Update attachment security status
 *
 * Record malware scan result and promote or reject the attachment
 */
export const updateSecurityStatus = <ThrowOnError extends boolean = false>(options: Options<UpdateSecurityStatusData, ThrowOnError>): RequestResult<UpdateSecurityStatusResponses, unknown, ThrowOnError> => (options.client ?? client).post<UpdateSecurityStatusResponses, unknown, ThrowOnError>({
    responseType: 'json',
    url: '/internal/attachments/{attachmentId}/security-status',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Create upload target
 *
 * Create an upload target for uploading attachment files
 */
export const createUploadTarget = <ThrowOnError extends boolean = false>(options: Options<CreateUploadTargetData, ThrowOnError>): RequestResult<CreateUploadTargetResponses, unknown, ThrowOnError> => (options.client ?? client).post<CreateUploadTargetResponses, unknown, ThrowOnError>({
    responseType: 'json',
    url: '/internal/attachments/createUploadTarget',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Upload file to upload target
 *
 * Upload file to upload target
 */
export const uploadToTarget = <ThrowOnError extends boolean = false>(options: Options<UploadToTargetData, ThrowOnError>): RequestResult<UploadToTargetResponses, unknown, ThrowOnError> => (options.client ?? client).put<UploadToTargetResponses, unknown, ThrowOnError>({
    responseType: 'json',
    url: '/attachments/upload/{id}',
    ...options
});

/**
 * Check a graph relationship
 *
 * Check a Keto permission: namespace, object, relation, and subject (subject_id, e.g. identity:<id>).
 */
export const checkRelationship = <ThrowOnError extends boolean = false>(options: Options<CheckRelationshipData, ThrowOnError>): RequestResult<CheckRelationshipResponses, unknown, ThrowOnError> => (options.client ?? client).post<CheckRelationshipResponses, unknown, ThrowOnError>({
    responseType: 'json',
    url: '/authorization/checkRelationship',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Ensure a graph relationship exists
 *
 * Idempotently create a relationship in the authorization graph (Ory Keto). Used by domain services to grant permissions and role members.
 */
export const ensureRelationship = <ThrowOnError extends boolean = false>(options: Options<EnsureRelationshipData, ThrowOnError>): RequestResult<EnsureRelationshipResponses, unknown, ThrowOnError> => (options.client ?? client).post<EnsureRelationshipResponses, unknown, ThrowOnError>({
    responseType: 'json',
    url: '/authorization/ensureRelationship',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Delete a graph relationship
 *
 * Idempotently delete a relationship from the authorization graph (Ory Keto).
 */
export const deleteRelationship = <ThrowOnError extends boolean = false>(options: Options<DeleteRelationshipData, ThrowOnError>): RequestResult<DeleteRelationshipResponses, unknown, ThrowOnError> => (options.client ?? client).post<DeleteRelationshipResponses, unknown, ThrowOnError>({
    responseType: 'json',
    url: '/authorization/deleteRelationship',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * List graph relationships
 *
 * List stored relationships for an object in the authorization graph.
 */
export const listRelationships = <ThrowOnError extends boolean = false>(options: Options<ListRelationshipsData, ThrowOnError>): RequestResult<ListRelationshipsResponses, unknown, ThrowOnError> => (options.client ?? client).post<ListRelationshipsResponses, unknown, ThrowOnError>({
    responseType: 'json',
    url: '/authorization/listRelationships',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});
