mutation CreateChecklistEntry($input: CreateChecklistEntryInput!) {
  createChecklistEntry(input: $input) {
    id
    checklistId
    title
    completed
    orderIndex
    createdById
    createdAt
  }
}
