export { auditColumns, idColumn } from "@/db/columns";
export {
  type Identity,
  type NewIdentity,
  Identities,
  type Space,
  type NewSpace,
  Spaces,
  type Item,
  type NewItem,
  Items,
  type Project,
  type NewProject,
  Projects,
  type Organization,
  type NewOrganization,
  Organizations,
  type Attachment,
  type NewAttachment,
  Attachments,
  type AuditLog,
  type NewAuditLog,
  AuditLogs,
} from "@/db/tables";
