export { auditColumns, idColumn } from "@/db/columns";
export {
  type Identity,
  type NewIdentity,
  Identities,
  type Space,
  type NewSpace,
  Spaces,
  type Item,
  type NewItem,
  Items,
  type Project,
  type NewProject,
  Projects,
  type Workspace,
  type NewWorkspace,
  Workspaces,
  type Attachment,
  type NewAttachment,
  Attachments,
  type AuditLog,
  type NewAuditLog,
  AuditLogs,
} from "@/db/tables";
