mutation CreateItemAttachmentUploadRequest(
  $input: CreateItemAttachmentUploadRequestInput!
) {
  createItemAttachmentUploadRequest(input: $input) {
    uploadRequestId
    url
    expiresAt
    headers {
      key
      value
    }
  }
}
