query GetItemAuditLogs($itemId: String!, $organizationId: String!) {
  getItemAuditLogs(itemId: $itemId, organizationId: $organizationId) {
    id
    entityType
    entityId
    action
    actorId
    actor {
      id
      fullName
      firstName
      middleName
      lastName
      createdAt
      updatedAt
    }
    organizationId
    createdAt
  }
}
