query GetItem($id: String!) {
  getItem(id: $id) {
    id
    description
    list {
      id
      name
    }
    parentItem {
      id
      name
    }
    name
    statusId
    priority
    dueDate
  }
}
