query GetListItems($listId: String!) {
  getListItems(listId: $listId) {
    status {
      id
      name
      orderIndex
      color
      type
    }
    items {
      description
      id
      name
      statusId
      priority
      dueDate
      hasChildren
      checklists {
        completedCount
        totalCount
      }
    }
  }
}
