name: api-gateway

replicaCount: 1

image:
  repository: pine/api-gateway
  tag: "0.1.0"
  pullPolicy: IfNotPresent

service:
  enabled: true
  port: 4000
  targetPort: 4000

secretRefs: []

tls:
  enabled: true
  secretName: api-gateway-tls
  mountPath: /certs

env:
  NODE_ENV: production
  API_GATEWAY_URL: https://api-gateway.pine.svc:4000
  IDENTITY_SERVICE_URL: https://identity.pine.svc:5000
  ATTACHMENT_SERVICE_URL: https://attachment.pine.svc:5003
  AUTHORIZATION_SERVICE_URL: https://authorization.pine.svc:5006
  API_GATEWAY_TLS_KEY_PATH: /certs/tls.key
  API_GATEWAY_TLS_CERT_PATH: /certs/tls.crt
  CA_CERT_PATH: /certs/ca.crt
