name: platform

replicaCount: 1

image:
  repository: pine/platform-service
  tag: "0.1.0"
  pullPolicy: IfNotPresent

service:
  enabled: true
  port: 5005
  targetPort: 5005

secretRefs:
  - platform-secrets

tls:
  enabled: true
  secretName: platform-tls
  mountPath: /certs

env:
  NODE_ENV: production
  NATS_URL: nats://nats.nats.svc:4222
  PLATFORM_SERVICE_URL: https://platform.pine.svc:5005
  AUTHORIZATION_SERVICE_URL: https://authorization.pine.svc:5006
  PLATFORM_SERVICE_TLS_KEY_PATH: /certs/tls.key
  PLATFORM_SERVICE_TLS_CERT_PATH: /certs/tls.crt
  CA_CERT_PATH: /certs/ca.crt
