query GetItemAttachments($itemId: String!) {
  getItemAttachments(itemId: $itemId) {
    id
    itemId
    attachmentId
    status
    processing {
      label
    }
    name
    originalName
    mimeType
    size
    createdById
    createdAt
  }
}
