export enum ItemPermissions {
  ViewItem = "item:view-item",
  EditItem = "item:edit-item",
  EditItemStatus = "item:edit-item-status",
  EditItemResolution = "item:edit-item-resolution",
  ArchiveItem = "item:archive-item",
  CreateAttachment = "item:create-attachment",
  ViewAttachment = "item:view-attachment",
  EditAttachment = "item:edit-attachment",
  ArchiveAttachment = "item:archive-attachment",
  CreateTask = "item:create-task",
  ViewTask = "item:view-task",
  EditTask = "item:edit-task",
  ArchiveTask = "item:archive-task",
  CreateComment = "item:create-comment",
  ViewComment = "item:view-comment",
  EditComment = "item:edit-comment",
  ArchiveComment = "item:archive-comment",
}
