export const TYPES = {
  Database: Symbol.for("Database"),
  Logger: Symbol.for("Logger"),
  Broker: Symbol.for("Broker"),
  Publisher: Symbol.for("Publisher"),
  OutboxRepository: Symbol.for("IOutboxRepository"),
  OutboxService: Symbol.for("IOutboxService"),
  OutboxWorker: Symbol.for("IOutboxWorker"),
  OutboxCleanupService: Symbol.for("IOutboxCleanupService"),
  OutboxCleanupWorker: Symbol.for("IOutboxCleanupWorker"),
  RetryPolicy: Symbol.for("IRetryPolicy"),
  HttpServer: Symbol.for("IHttpServer"),
  IdentityRepository: Symbol.for("IIdentityRepository"),
  ItemRepository: Symbol.for("IItemRepository"),
  ItemAssigneeRepository: Symbol.for("IItemAssigneeRepository"),
  ItemService: Symbol.for("IItemService"),
  ProjectRepository: Symbol.for("IProjectRepository"),
  ProjectService: Symbol.for("IProjectService"),
  SpaceRepository: Symbol.for("ISpaceRepository"),
  SpaceService: Symbol.for("ISpaceService"),
  StatusRepository: Symbol.for("IStatusRepository"),
  StatusService: Symbol.for("IStatusService"),
  AuthorizationClient: Symbol.for("IAuthorizationClient"),
  ItemsIdentitySyncConsumer: Symbol.for("ItemsIdentitySyncConsumer"),
} as const;
