mutation CreateChecklist($input: CreateChecklistInput!) {
  createChecklist(input: $input) {
    id
    itemId
    name
    createdById
    createdAt
    completedCount
    totalCount
    entries {
      id
      checklistId
      title
      completed
      orderIndex
      createdById
      createdAt
    }
  }
}
