apiVersion: v1
kind: Service
metadata:
  name: seaweedfs
  labels:
    app.kubernetes.io/name: seaweedfs
    app.kubernetes.io/part-of: pine
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: seaweedfs
  ports:
    - name: s3
      port: 8333
      targetPort: s3
    - name: filer
      port: 8888
      targetPort: filer
    - name: master
      port: 9333
      targetPort: master
