apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: attachment
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: openbao
    kind: SecretStore
  target:
    name: attachment-secrets
    creationPolicy: Owner
  data:
    - secretKey: POSTGRES_ATTACHMENT_PASSWORD
      remoteRef:
        key: pine/attachment
        property: postgres_attachment_password
    - secretKey: S3_ACCESS_KEY
      remoteRef:
        key: pine/attachment
        property: s3_access_key
    - secretKey: S3_SECRET_KEY
      remoteRef:
        key: pine/attachment
        property: s3_secret_key
