apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: platform
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: openbao
    kind: SecretStore
  target:
    name: platform-secrets
    creationPolicy: Owner
  data:
    - secretKey: POSTGRES_PLATFORM_PASSWORD
      remoteRef:
        key: pine/platform
        property: postgres_platform_password
