mutation CreateOrganization($input: CreateOrganizationInput!) {
  createOrganization(input: $input) {
    id
    tenantId
    parentOrganizationId
    officeTypeId
    name
    slug
    description
    isActive
    createdAt
    updatedAt
  }
}
