query GetOrganization($id: String!) {
  getOrganization(id: $id) {
    id
    tenantId
    parentOrganizationId
    officeTypeId
    name
    slug
    description
    isActive
    createdAt
    updatedAt
  }
}
